# Generated by Django 4.2.30 on 2026-08-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Anchor used in the public URL (e.g. #sensor). Changing it breaks links people have already shared.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Sections are shown from lowest to highest.",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished categories are hidden from the public page.",
                    ),
                ),
                ("label_es", models.CharField(max_length=120)),
                ("label_en", models.CharField(blank=True, max_length=120)),
                ("label_pt", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name": "FAQ category",
                "verbose_name_plural": "FAQ categories",
                "db_table": "faq_category",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FaqQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Questions are shown from lowest to highest within a category.",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished questions are hidden from the public page.",
                    ),
                ),
                ("question_es", models.CharField(max_length=300)),
                ("answer_es", models.TextField()),
                ("question_en", models.CharField(blank=True, max_length=300)),
                ("answer_en", models.TextField(blank=True)),
                ("question_pt", models.CharField(blank=True, max_length=300)),
                ("answer_pt", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.faqcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ question",
                "verbose_name_plural": "FAQ questions",
                "db_table": "faq_question",
                "ordering": ["category__order", "order", "id"],
            },
        ),
    ]
