# Generated by Django 4.2.30 on 2026-07-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                ("sensor_type", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("specific_location", models.CharField(blank=True, max_length=255)),
                ("locality", models.CharField(blank=True, max_length=255)),
                ("environment_type", models.CharField(blank=True, max_length=255)),
                ("connectivity", models.CharField(blank=True, max_length=255)),
                ("power_source", models.CharField(blank=True, max_length=255)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("responsible", models.CharField(blank=True, max_length=255)),
                ("contact_info", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "station",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="details",
                        to="api.stations",
                    ),
                ),
            ],
            options={
                "verbose_name": "station details",
                "verbose_name_plural": "station details",
                "db_table": "station_details",
            },
        ),
    ]
