# Generated by Django 4.2.30 on 2026-07-29 18:25
"""Register StationOverride, creating its table only where nothing else has.

``station_overrides`` is provisioned by respira-data: its ``warehouse_bootstrap``
flow runs ``pipelines/sql/04_station_overrides_table.sql`` as ``dbtuser``,
because the pipeline reads the table through the ``respira_webapp`` dbt source
and has to be able to establish its own runtime dependencies. The backend role
holds CRUD on the table and schema USAGE, but no CREATE on ``respira_gold``.

So this migration cannot do what a ``CreateModel`` operation normally does.
Against a deployed database it would fail twice over: the table already exists,
and the role could not create it there anyway. But the model still has to be
registered in Django's migration state, or every later migration that touches
it — and ``makemigrations`` — would see a model that Django believes does not
exist.

``SeparateDatabaseAndState`` splits exactly that:

* the *state* half always runs, so Django's history is identical to what a
  plain ``CreateModel`` would have produced;
* the *database* half is guarded, and issues DDL only when the table is
  genuinely absent — a fresh dev database, CI, or SQLite, where no pipeline
  ran to create it first.

The guard reads ``pg_catalog`` rather than ``information_schema`` for the same
reason api/schema_moves.py does: ``information_schema`` only lists tables the
current role holds a privilege on, so a table provisioned by another role can
read as *missing* there, and "missing" is indistinguishable from "not yet
created". Getting that wrong would make this migration attempt a CREATE it is
not allowed to issue, against a table that is already there.

The table is looked for in every non-internal schema, not just the one it
should end up in. At this point in the migration history 0019 has not run yet,
so a table created here lands unqualified in whatever schema search_path puts
first; and on a database provisioned by respira-data it already sits in
``respira_gold``. Either way it exists, and this migration must not create a
second copy.
"""

from django.db import migrations, models
from django.db.migrations.state import ProjectState
import django.utils.timezone

from api.schema_moves import PG_INTERNAL_SCHEMAS, is_postgresql

TABLE_NAME = "station_overrides"

# The model as Django records it. Used twice below: as the migration's state
# half, and — rendered through a ProjectState — as the source of the DDL the
# database half issues, so the two can never disagree.
STATE_OPERATIONS = [
    migrations.CreateModel(
        name="StationOverride",
        fields=[
            (
                "id",
                models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID",
                ),
            ),
            ("station_code", models.CharField(db_index=True, max_length=255)),
            ("field", models.CharField(max_length=255)),
            ("value", models.CharField(max_length=255)),
            ("note", models.TextField(blank=True)),
            (
                "change_date",
                models.DateTimeField(default=django.utils.timezone.now),
            ),
            ("processed", models.BooleanField(default=False)),
        ],
        options={
            "db_table": TABLE_NAME,
            "ordering": ("-change_date",),
        },
    ),
    migrations.AddConstraint(
        model_name="stationoverride",
        constraint=models.UniqueConstraint(
            fields=("station_code", "field"),
            name="uniq_station_override_code_field",
        ),
    ),
]


def _table_exists(schema_editor):
    """True when some schema already holds a table called station_overrides."""
    if not is_postgresql(schema_editor):
        # SQLite has a single namespace and no pipeline to provision anything,
        # so the ordinary introspection answer is the right one.
        return TABLE_NAME in schema_editor.connection.introspection.table_names()

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM pg_catalog.pg_class c
            JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = %s
              AND c.relkind IN ('r', 'p')
              AND n.nspname NOT IN %s
            LIMIT 1
            """,
            [TABLE_NAME, PG_INTERNAL_SCHEMAS],
        )
        return cursor.fetchone() is not None


def _historical_model():
    """The StationOverride model exactly as the state half below defines it.

    Rendered from a ModelState built from those same operations, rather than
    from the ``apps`` passed to a RunPython: inside SeparateDatabaseAndState
    the database half receives ``from_state`` — the state *before* this
    migration — where the model does not exist yet.

    Going through the state operations is what keeps the two halves from
    drifting: the DDL issued here is generated from the same field list,
    db_table, constraint and index that Django records in its history, so a
    database created by this migration is byte-identical to the one
    respira-data provisions.
    """
    project_state = ProjectState()
    for operation in STATE_OPERATIONS:
        operation.state_forwards("api", project_state)
    return project_state.apps.get_model("api", "StationOverride")


def create_table_if_absent(apps, schema_editor):
    if _table_exists(schema_editor):
        return
    schema_editor.create_model(_historical_model())


def drop_table_if_present(apps, schema_editor):
    """Reverse of the database half.

    Dropping a table this migration did not create would destroy data owned by
    the pipeline side, so the same guard applies in reverse: only drop what is
    actually here to drop, and let a missing table reverse cleanly.
    """
    if not _table_exists(schema_editor):
        return
    schema_editor.delete_model(_historical_model())


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_stationdetails"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_table_if_absent,
                    drop_table_if_present,
                ),
            ],
            state_operations=STATE_OPERATIONS,
        ),
    ]
