# Generated by Django 4.2.30 on 2026-07-29 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_stationdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_code", models.CharField(db_index=True, max_length=255)),
                ("field", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                (
                    "change_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "station_overrides",
                "ordering": ("-change_date",),
            },
        ),
        migrations.AddConstraint(
            model_name="stationoverride",
            constraint=models.UniqueConstraint(
                fields=("station_code", "field"),
                name="uniq_station_override_code_field",
            ),
        ),
    ]
