# Generated by Django 4.2.30 on 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_seed_faq"),
        ("api", "0005_stationoverride"),
    ]

    operations = []
