# Generated by Django 4.2.30 on 2026-08-19 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_institutionuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aqi_value",
                    models.FloatField(
                        help_text="AQI reading that triggered the alert."
                    ),
                ),
                (
                    "alert_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Threshold in force when the alert fired, copied from the institution's alert configuration so later edits to that configuration don't rewrite history.",
                        null=True,
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Left empty while the event is still ongoing.",
                        null=True,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.institution",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="institution_alerts",
                        to="api.stations",
                    ),
                ),
            ],
            options={
                "db_table": "institution_alert",
                "ordering": ("-triggered_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.TextField(help_text="The action taken by the institution."),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: the alert this action responded to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to="api.institutionalert",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="api.institution",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="action_logs",
                        to="api.stations",
                    ),
                ),
            ],
            options={
                "db_table": "action_log",
                "ordering": ("-timestamp", "-id"),
            },
        ),
    ]
