# Generated by Django 4.2.30 on 2026-08-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_institutionuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=100)),
                ("emoji", models.CharField(blank=True, max_length=8)),
            ],
            options={
                "db_table": "sensitive_group",
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="InstitutionAlertConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "alert_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="AQI value above which an alert is triggered.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_config",
                        to="api.institution",
                    ),
                ),
                (
                    "sensitive_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alert_configs",
                        to="api.sensitivegroup",
                    ),
                ),
            ],
            options={
                "db_table": "institution_alert_config",
            },
        ),
    ]
