# Generated by Django 4.2.30 on 2026-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_seed_sensitive_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceFollower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installation_id",
                    models.UUIDField(
                        editable=False,
                        help_text="UUIDv4 generated by the app on first launch.",
                        unique=True,
                    ),
                ),
                (
                    "station_code",
                    models.CharField(
                        db_index=True,
                        help_text="The pipeline's stable natural key for the followed station.",
                        max_length=255,
                    ),
                ),
                (
                    "push_token",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Current FCM/APNs token; blank until the app registers one.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "device_follower",
                "ordering": ("-updated_at",),
            },
        ),
    ]
