# Generated by Django 4.2.30 on 2026-08-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_institutionalert_actionlog'),
        ('api', '0012_seed_sensitive_groups'),
    ]

    operations = [
    ]
