# Generated by Django 4.2.30 on 2026-08-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_devicefollower'),
        ('api', '0013_merge_0011_actionlog_0012_sensitive_groups'),
    ]

    operations = [
    ]
