"""Split the installation out of the follower row, so a device can follow many.

The old shape put ``installation_id`` and ``push_token`` on the follower and
made ``installation_id`` unique — which is what enforced "one device follows one
station". Following several means dropping that uniqueness, and once a device
has N rows the token cannot live on them: it would be stored N times, every
write would have to keep the copies in step, and a notification fan-out would
deliver N times to the same phone.

So the installation becomes its own row, the follower points at it, and
uniqueness moves to the pair ``(installation, station_code)`` — which is what
keeps a repeated follow idempotent instead of duplicating.
"""

import django.db.models.deletion
from django.db import migrations, models


def create_installations(apps, schema_editor):
    """Give every existing follower row an installation to point at.

    ``installation_id`` was unique on the follower, so this is one-to-one; the
    ``get_or_create`` is defensive rather than load-bearing. The push token
    moves across with it.

    The old UUID is read from ``installation_id_value``, not
    ``installation_id``: by this point the foreign key added above owns the
    latter as its attribute name, and reading it would silently yield the
    unset key rather than the UUID we are migrating.
    """
    DeviceInstallation = apps.get_model("api", "DeviceInstallation")
    DeviceFollower = apps.get_model("api", "DeviceFollower")

    for follower in DeviceFollower.objects.all().iterator():
        installation, _ = DeviceInstallation.objects.get_or_create(
            installation_id=follower.installation_id_value,
            defaults={"push_token": follower.push_token or ""},
        )
        follower.installation = installation
        follower.save(update_fields=["installation"])


def restore_installation_ids(apps, schema_editor):
    """Fold the installation back onto the follower row.

    Only possible while the data still fits the old shape. Once a device
    follows a second station there is no ``installation_id``-unique row set to
    go back to, and silently dropping the extra follows would lose a user's
    choices — so this refuses instead.

    By the time this runs in reverse, ``installation_id_value`` and
    ``push_token`` are back on the follower as nullable/defaulted columns (see
    the ``AlterField`` above), so there is somewhere to put the values; the
    NOT NULL is restored afterwards, once every row has one.
    """
    DeviceInstallation = apps.get_model("api", "DeviceInstallation")
    DeviceFollower = apps.get_model("api", "DeviceFollower")

    multi = (
        DeviceInstallation.objects.annotate(n=models.Count("follows"))
        .filter(n__gt=1)
        .count()
    )
    if multi:
        raise RuntimeError(
            f"{multi} installation(s) follow more than one station; reversing "
            "this migration would discard those follows. Remove the extra "
            "follows first if you really mean to go back."
        )

    for follower in DeviceFollower.objects.select_related("installation").iterator():
        follower.installation_id_value = follower.installation.installation_id
        follower.push_token = follower.installation.push_token
        follower.save(update_fields=["installation_id_value", "push_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_merge_20260826_1744"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installation_id",
                    models.UUIDField(
                        editable=False,
                        help_text="UUIDv4 generated by the app on first launch.",
                        unique=True,
                    ),
                ),
                (
                    "push_token",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "Current FCM/APNs token; blank until the app registers one."
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "device_installation",
                "ordering": ("-updated_at",),
            },
        ),
        # Renamed *before* the foreign key is added, not after: a FK named
        # `installation` gets the column `installation_id`, which is exactly
        # the name the old UUID field already occupies. Renaming first frees
        # it. The old value stays readable until the data migration has copied
        # it across, and is dropped at the end.
        migrations.RenameField(
            model_name="devicefollower",
            old_name="installation_id",
            new_name="installation_id_value",
        ),
        # Nullable only so that this migration can be reversed. Reversing the
        # `RemoveField` at the end re-adds this column, and a NOT NULL column
        # with no default cannot be added to a table that already has rows —
        # which used to make the whole reversal fail before
        # `restore_installation_ids` ever ran. Reversing *this* operation is
        # what puts the NOT NULL back, and it runs after the restore has filled
        # every row.
        migrations.AlterField(
            model_name="devicefollower",
            name="installation_id_value",
            field=models.UUIDField(
                editable=False,
                null=True,
                unique=True,
                help_text="UUIDv4 generated by the app on first launch.",
            ),
        ),
        # Nullable first: the rows that need it are filled in by the data
        # migration below, and only then is the column made required.
        migrations.AddField(
            model_name="devicefollower",
            name="installation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follows",
                to="api.deviceinstallation",
                help_text="The installation that follows this station.",
            ),
        ),
        migrations.RunPython(create_installations, restore_installation_ids),
        migrations.AlterField(
            model_name="devicefollower",
            name="installation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follows",
                to="api.deviceinstallation",
                help_text="The installation that follows this station.",
            ),
        ),
        migrations.RemoveField(
            model_name="devicefollower",
            name="installation_id_value",
        ),
        migrations.RemoveField(
            model_name="devicefollower",
            name="push_token",
        ),
        migrations.AlterModelOptions(
            name="devicefollower",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="devicefollower",
            constraint=models.UniqueConstraint(
                fields=("installation", "station_code"),
                name="uniq_follow_per_installation",
            ),
        ),
    ]
