# Generated by Django 4.2.30 on 2026-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_device_installation_multi_follow"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_code",
                    models.CharField(
                        db_index=True,
                        help_text="The pipeline's stable natural key for the station alerted about.",
                        max_length=255,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="AQI level key at the time of the alert, e.g. 'unhealthy'.",
                        max_length=32,
                    ),
                ),
                (
                    "aqi",
                    models.FloatField(
                        help_text="The reading that triggered the alert."
                    ),
                ),
                (
                    "recipients",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many devices the push service accepted the alert for.",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sensor_alert",
                "ordering": ("-sent_at",),
            },
        ),
    ]
