# Generated by Django 4.2.30 on 2026-09-21 17:33
#
# Lets one institution lease several sensors (RES-459).
#
# The only change is dropping the UNIQUE index on `institution_id`, so an
# institution may hold more than one contract row — one per sensor. Purely
# widening: every existing row is already valid under the looser rule, so no
# data migration is needed and single-sensor institutions keep working
# untouched.
#
# `station` stays OneToOne on purpose. That unique index is what guarantees a
# sensor belongs to exactly one institution, and therefore what keeps one
# institution's data out of another's dashboard.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_push_notification_window"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutioncontract",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="api.institution",
            ),
        ),
    ]
