services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - proxy_nw
    volumes:
      - static_volume:/static
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:${BACKEND_PORT}/api/health/ | grep -q 200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        -  PUBLIC_REGION_DEFAULT_ID=8495471280173798472
        -  PUBLIC_BACKEND_URL=${BACKEND_URL}
        -  SITE_URL=${SITE_URL}
        -  PUBLIC_GTAG=${PUBLIC_GTAG}
    restart: always
    environment:
      PUBLIC_REGION_DEFAULT_ID: 8495471280173798472
      PUBLIC_BACKEND_URL: ${BACKEND_URL}
      FRONTEND_PORT: ${FRONTEND_PORT}
      SITE_URL: ${SITE_URL}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_KEY: ${SMTP_KEY}
    networks:
      - frontend_nw
      - proxy_nw
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:${FRONTEND_PORT} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  proxy:
    build:
      context: ./proxy
      target: ${ENVIRONMENT}
    restart: always
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: ${BACKEND_PORT}
      CERT_NAME: ${CERT_NAME}
      FRONTEND_HOST: frontend
      FRONTEND_PORT: ${FRONTEND_PORT}
      SERVER_HOST: ${SERVER_HOST}
    ports:
      - "${PROXY_PORT}:80"
      - 443:443
    networks:
      - proxy_nw
    volumes:
      - static_volume:/static
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  static_volume:

networks:
  proxy_nw:
  frontend_nw:
