"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path
from typing import Any

load_dotenv()


def _quote_postgres_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("BACKEND_SECRET_KEY", "respira-backend-dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("BACKEND_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "testserver",
    "159.65.227.146",
    "proyectorespira.net",
    ".proyectorespira.net",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "api",
]

REST_FRAMEWORK = {"DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema"}

SPECTACULAR_SETTINGS = {
    "TITLE": "RespiraAPI",
    "DESCRIPTION": "This is the Respira API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

CORS_ORIGIN_ALLOW_ALL = False

CORS_ORIGIN_WHITELIST = ["http://proyectorespira.net", "http://dev.proyectorespira.net"]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

postgres_config: dict[str, str | None] = {
    "NAME": os.getenv("BACKEND_POSTGRES_DB"),
    "USER": os.getenv("BACKEND_POSTGRES_USER"),
    "PASSWORD": os.getenv("BACKEND_POSTGRES_PASSWORD"),
    "HOST": os.getenv("BACKEND_POSTGRES_HOST"),
    "PORT": os.getenv("BACKEND_POSTGRES_PORT"),
}

DATABASES: dict[str, dict[str, Any]]

if all(postgres_config.values()):
    postgres_config_clean = {
        key: value for key, value in postgres_config.items() if value is not None
    }
    db_options: dict[str, str] = {}
    sslmode = os.getenv("BACKEND_POSTGRES_SSLMODE")
    if sslmode:
        db_options["sslmode"] = sslmode

    sslrootcert = os.getenv("BACKEND_POSTGRES_SSLROOTCERT")
    if sslrootcert:
        db_options["sslrootcert"] = sslrootcert

    sslcert = os.getenv("BACKEND_POSTGRES_SSLCERT")
    if sslcert:
        db_options["sslcert"] = sslcert

    sslkey = os.getenv("BACKEND_POSTGRES_SSLKEY")
    if sslkey:
        db_options["sslkey"] = sslkey

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            **postgres_config_clean,
            "OPTIONS": db_options,
        }
    }

    db_schemas = [
        schema.strip()
        for schema in os.getenv("BACKEND_POSTGRES_SCHEMA", "respira_gold").split(",")
        if schema.strip()
    ]

    if db_schemas:
        quoted_schemas = [_quote_postgres_identifier(schema) for schema in db_schemas]
        if "public" not in {schema.lower() for schema in db_schemas}:
            quoted_schemas.append("public")
        default_db = DATABASES["default"]
        db_options_map = default_db.setdefault("OPTIONS", {})
        db_options_map["options"] = f"-c search_path={','.join(quoted_schemas)}"
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CORS configuration
# See https://github.com/adamchainz/django-cors-headers for details

cors_allowed_origins = os.getenv("BACKEND_CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in cors_allowed_origins.split(",") if origin.strip()
]
